env:
  VERSION: "${BUILDKITE_BRANCH}"

steps:
  - label: "Build InferX Platform & NA Images "
    key: build-platform-na
    agents:
      queue: cpu_queue_postmerge
    commands:
      - echo "Building InferX v${VERSION}"
      - echo "Installing build dependencies..."
      - |
          apt-get update -qq
          apt-get install -y -qq software-properties-common tzdata
          add-apt-repository ppa:deadsnakes/ppa -y
          apt-get update -qq
          apt-get install -y -qq build-essential pkg-config libssl-dev protobuf-compiler curl python3.12 python3.12-dev python3.12-venv docker.io
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata >/dev/null
      - echo "Pinning python to 3.12..."
      - |
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1
          update-alternatives --set python3 /usr/bin/python3.12
          update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1
          update-alternatives --set python /usr/bin/python3.12
          python3 --version
          python --version
      - echo "Installing Rust..."
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - . $$HOME/.cargo/env
      - rustc --version

      - echo "Building svc binary..."
      - cargo +stable build --bin svc

      - echo "Building ixctl binary..."
      - OPENSSL_STATIC=1 cargo +stable build --bin ixctl

      - echo "Preparing Docker build context..."
      - mkdir -p ./target/svc/inferx/config
      - cp ./target/debug/svc ./target/svc/
      - cp ./deployment/svc.Dockerfile ./target/svc/Dockerfile
      - cp nodeconfig/node*.json ./target/svc/inferx/config/ || echo "No node config"
      - cp ./deployment/svc-entrypoint.sh ./target/svc/svc-entrypoint.sh
      - cp onenode_logging_config.yaml ./target/svc/ || echo "No logging config"

      - echo "Building Docker image..."
      - docker build --build-arg UBUNTU_VERSION=22.04 -f ./target/svc/Dockerfile -t remodlai/inferx_platform:${VERSION} ./target/svc
      - docker tag remodlai/inferx_platform:${VERSION} remodlai/inferx_na:${VERSION}
      - echo "Logging into Docker Hub..."
      - buildkite-agent secret get DOCKERHUB_TOKEN | docker login -u brianremodl --password-stdin
      - echo "Pushing images..."
      - docker push remodlai/inferx_platform:${VERSION}
      - docker push remodlai/inferx_na:${VERSION}

      - echo "✅ Platform and NA images built!"

  - label: "Build Dashboard Image"
    key: build-dashboard
    agents:
      queue: cpu_queue_postmerge
    commands:
      - echo "Building InferX Dashboard v${VERSION}"
      - echo "Installing Docker CLI..."
      - |
          apt-get update -qq
          apt-get install -y -qq docker.io
      - mkdir -p ./target/dashboard
      - rm -rf ./target/dashboard/*
      - cp -rL ./dashboard/* ./target/dashboard/
      - cp ./deployment/dashboard.Dockerfile ./target/dashboard/Dockerfile

      - echo "Building Docker image..."
      - docker build -f ./target/dashboard/Dockerfile -t remodlai/inferx_dashboard:${VERSION} ./target/dashboard
      - echo "Logging into Docker Hub..."
      - buildkite-agent secret get DOCKERHUB_TOKEN | docker login -u brianremodl --password-stdin
      - echo "Pushing image..."
      - docker push remodlai/inferx_dashboard:${VERSION}

      - echo "✅ Dashboard image built and pushed!"

  - label: "Build PostgreSQL Image"
    key: build-postgres
    agents:
      queue: cpu_queue_postmerge
    commands:
      - echo "Building InferX PostgreSQL v${VERSION}"
      - echo "Installing Docker CLI..."
      - |
          apt-get update -qq
          apt-get install -y -qq docker.io
      - mkdir -p ./target/postgres
      - rm -rf ./target/postgres/*
      - cp ./dashboard/sql/*.sql ./target/postgres/
      - cp ./deployment/postgres-entrypoint.sh ./target/postgres/postgres-entrypoint.sh
      - cp ./deployment/postgres.Dockerfile ./target/postgres/Dockerfile

      - echo "Building Docker image..."
      - docker build -f ./target/postgres/Dockerfile -t remodlai/inferx_postgres:${VERSION} ./target/postgres
      - echo "Logging into Docker Hub..."
      - buildkite-agent secret get DOCKERHUB_TOKEN | docker login -u brianremodl --password-stdin
      - echo "Pushing image..."
      - docker push remodlai/inferx_postgres:${VERSION}

      - echo "✅ PostgreSQL image built and pushed!"

  - wait

  - label: "Build Complete"
    command: |
      echo "✅ All InferX images built successfully for version ${VERSION}!"
      echo ""
      echo "Images pushed to Docker Hub:"
      echo "  - remodlai/inferx_platform:${VERSION}"
      echo "  - remodlai/inferx_na:${VERSION}"
      echo "  - remodlai/inferx_dashboard:${VERSION}"
      echo "  - remodlai/inferx_postgres:${VERSION}"
      echo ""
      echo "To deploy on EKS, update the image tags in k8s manifests to ${VERSION}"

secrets:
  - DOCKERHUB_TOKEN
