env:
  VERSION: "${BUILDKITE_BRANCH}"

steps:
  - label: "Build InferX Platform & NA Images"
    key: build-platform-na
    agents:
      queue: cpu_queue_postmerge
    commands:
      - echo "Building InferX v${VERSION}"
      - echo "Installing build dependencies..."
      - |
          set -euo pipefail
          apt-get update -qq
          apt-get install -y -qq software-properties-common tzdata
          add-apt-repository ppa:deadsnakes/ppa -y
          apt-get update -qq
          apt-get install -y -qq build-essential pkg-config libssl-dev protobuf-compiler curl python3.12 python3.12-dev python3.12-venv docker.io
          ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata >/dev/null
      - echo "Installing Rust..."
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - . $$HOME/.cargo/env
      - rustc --version

      - echo "Building svc binary..."
      - cargo +stable build --bin svc

      - echo "Building ixctl binary..."
      - OPENSSL_STATIC=1 cargo +stable build --bin ixctl

      - echo "Preparing Docker build context..."
      - mkdir -p ./target/svc/inferx/config
      - cp ./target/debug/svc ./target/svc/
      - cp ./deployment/svc.Dockerfile ./target/svc/Dockerfile
      - cp nodeconfig/node*.json ./target/svc/inferx/config/ || echo "No node config"
      - cp ./deployment/svc-entrypoint.sh ./target/svc/svc-entrypoint.sh
      - cp onenode_logging_config.yaml ./target/svc/ || echo "No logging config"

      - echo "Building Docker image..."
      - cd ./target/svc
      - docker build --build-arg UBUNTU_VERSION=22.04 -t remodlai/inferx_platform:${VERSION} .
      - docker tag remodlai/inferx_platform:${VERSION} remodlai/inferx_na:${VERSION}
      - echo "Pushing images..."
      - docker push remodlai/inferx_platform:${VERSION}
      - docker push remodlai/inferx_na:${VERSION}

      - echo "✅ Platform and NA images built!"
    plugins:
      - docker#v5.11.0:
          image: ubuntu:22.04
          environment:
            - DEBIAN_FRONTEND=noninteractive
            - TZ=Etc/UTC
            - PYO3_PYTHON=python3.12
          mount-buildkite-agent: true
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
      - docker-login#v3.0.0:
          username: brianremodl
          password-env: DOCKERHUB_TOKEN
    secrets:
      - DOCKERHUB_TOKEN

  - label: "Build Dashboard Image"
    key: build-dashboard
    agents:
      queue: cpu_queue_postmerge
    commands:
      - echo "Building InferX Dashboard v${VERSION}"
      - mkdir -p ./target/dashboard
      - rm -rf ./target/dashboard/*
      - cp -rL ./dashboard/* ./target/dashboard/
      - cp ./deployment/dashboard.Dockerfile ./target/dashboard/Dockerfile

      - echo "Building Docker image..."
      - cd ./target/dashboard
      - docker build -t remodlai/inferx_dashboard:${VERSION} .
      - echo "Pushing image..."
      - docker push remodlai/inferx_dashboard:${VERSION}

      - echo "✅ Dashboard image built and pushed!"
    plugins:
      - docker#v5.11.0:
          image: ubuntu:22.04
          environment:
            - DEBIAN_FRONTEND=noninteractive
            - TZ=Etc/UTC
            - PYO3_PYTHON=python3.12
          mount-buildkite-agent: true
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
      - docker-login#v3.0.0:
          username: brianremodl
          password-env: DOCKERHUB_TOKEN
    secrets:
      - DOCKERHUB_TOKEN

  - label: "Build PostgreSQL Image"
    key: build-postgres
    agents:
      queue: cpu_queue_postmerge
    commands:
      - echo "Building InferX PostgreSQL v${VERSION}"
      - mkdir -p ./target/postgres
      - rm -rf ./target/postgres/*
      - cp ./dashboard/sql/*.sql ./target/postgres/
      - cp ./deployment/postgres-entrypoint.sh ./target/postgres/postgres-entrypoint.sh
      - cp ./deployment/postgres.Dockerfile ./target/postgres/Dockerfile

      - echo "Building Docker image..."
      - cd ./target/postgres
      - docker build -t remodlai/inferx_postgres:${VERSION} .
      - echo "Pushing image..."
      - docker push remodlai/inferx_postgres:${VERSION}

      - echo "✅ PostgreSQL image built and pushed!"
    plugins:
      - docker#v5.11.0:
          image: ubuntu:22.04
          environment:
            - DEBIAN_FRONTEND=noninteractive
            - TZ=Etc/UTC
            - PYO3_PYTHON=python3.12
          mount-buildkite-agent: true
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
      - docker-login#v3.0.0:
          username: brianremodl
          password-env: DOCKERHUB_TOKEN
    secrets:
      - DOCKERHUB_TOKEN

  - wait

  - label: "Build Complete"
    command: |
      echo "✅ All InferX images built successfully for version ${VERSION}!"
      echo ""
      echo "Images pushed to Docker Hub:"
      echo "  - remodlai/inferx_platform:${VERSION}"
      echo "  - remodlai/inferx_na:${VERSION}"
      echo "  - remodlai/inferx_dashboard:${VERSION}"
      echo "  - remodlai/inferx_postgres:${VERSION}"
      echo ""
      echo "To deploy on EKS, update the image tags in k8s manifests to ${VERSION}"
