apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - args:
        - start-dev
        - --verbose
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://inferx-keycloak-db-use1.c89icmiacj0k.us-east-1.rds.amazonaws.com:5432/keycloakdb
        - name: KC_DB_USERNAME
          value: postgres
        - name: KC_DB_PASSWORD
          value: inferxdbpass123
        - name: KC_HTTP_ENABLED
          value: 'true'
        - name: KC_PROXY
          value: edge
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: 'false'
        - name: KC_HOSTNAME_STRICT
          value: 'false'
        - name: KC_HTTP_RELATIVE_PATH
          value: /authn
        image: quay.io/keycloak/keycloak:latest
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 8080
      nodeSelector:
        inferx-role: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
  - nodePort: 31260
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
